### ISSUE TITLE
Error in og:image path generation token

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#1752]
```
rror: Call to a member function getFileUri() on null in find_styled_image_url() (line 174 of /mnt/www/html/ncigovcdode118/docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc) #0 /mnt/www/html/ncigovcdode118/docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc(142): find_styled_image_url(NULL, 'cgov_social_med...') #1 /mnt/www/html/ncigovcdode118/docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc(101): get_social_image_path_from_media(Object(Drupal\media\Entity\Media)) #2 /mnt/www/html/ncigovcdode118/docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc(44): get_meta_og_image_token(Array) #3 [internal function]: cgov_metatag_tokens('cgov_tokens', Array, Array, Array, Object(Drupal\Core\Render\BubbleableMetadata)) #4 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('cgov_metatag_to...', Array) #5 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Utility/Token.php(304): Drupal\Core\Extension\ModuleHandler->invokeAll('tokens', Array) #6 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Utility/Token.php(196): Drupal\Core\Utility\Token->generate('cgov_tokens', Array, Array, Array, Object(Drupal\Core\Render\BubbleableMetadata)) #7 /mnt/www/html/ncigovcdode118/docroot/modules/contrib/metatag/src/MetatagToken.php(52): Drupal\Core\Utility\Token->replace('[cgov_tokens:cg...', Array, Array, Object(Drupal\Core\Render\BubbleableMetadata)) #8 /mnt/www/html/ncigovcdode118/docroot/modules/contrib/metatag/src/MetatagManager.php(538): Drupal\metatag\MetatagToken->replace('[cgov_tokens:cg...', Array, Array) #9 /mnt/www/html/ncigovcdode118/docroot/modules/contrib/metatag/src/MetatagManager.php(465): Drupal\metatag\MetatagManager->generateRawElements(Array, Object(Drupal\node\Entity\Node)) #10 /mnt/www/html/ncigovcdode118/docroot/modules/contrib/metatag/metatag.module(461): Drupal\metatag\MetatagManager->generateElements(Array, Object(Drupal\node\Entity\Node)) #11 /mnt/www/html/ncigovcdode118/docroot/modules/contrib/metatag/metatag.module(240): metatag_get_tags_from_route() #12 /mnt/www/html/ncigovcdode118/docroot/modules/contrib/metatag/metatag.module(209): _metatag_remove_duplicate_entity_tags(Array) #13 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(539): metatag_entity_view_alter(Array, Object(Drupal\node\Entity\Node), Object(Drupal\Core\Entity\Entity\EntityViewDisplay)) #14 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(308): Drupal\Core\Extension\ModuleHandler->alter('node_view', Array, Object(Drupal\node\Entity\Node), Object(Drupal\Core\Entity\Entity\EntityViewDisplay)) #15 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(242): Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) #16 [internal function]: Drupal\Core\Entity\EntityViewBuilder->build(Array) #17 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Render/Renderer.php(378): call_user_func(Array, Array) #18 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #19 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\Core\Render\Renderer->render(Array, false) #20 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() #21 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #22 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #23 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #24 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #25 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #26 /mnt/www/html/ncigovcdode118/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent)) #27 /mnt/www/html/ncigovcdode118/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #28 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #30 /mnt/www/html/ncigovcdode118/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #31 /mnt/www/html/ncigovcdode118/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true) #32 /mnt/www/html/ncigovcdode118/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true) #33 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #34 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #35 /mnt/www/html/ncigovcdode118/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #36 /mnt/www/html/ncigovcdode118/docroot/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #37 /mnt/www/html/ncigovcdode118/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #38 {main}.
```

**Comment by sarinapadilla** [comment]
This was closed with PR #1746
