### ISSUE TITLE
Error messages when rebuilding front end

### ISSUE THREAD

**Issue by daquinohd** [NCIOCPL/cgov-digital-platform#1785]
When running `source:build:frontend-reqs`:
```
> node lib/install.js
The `/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
    mozjpeg pre-build test failed
    compiling from source
    Error: autoreconf -fiv && ./configure --disable-shared --prefix="/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/mozjpeg/vendor" --bindir="/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/mozjpeg/vendor" --libdir="/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/mozjpeg/vendor" && make --jobs=6 && make install --jobs=6
Command failed: autoreconf -fiv
/bin/sh: 1: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

When running `source:build:frontend-assets`:
```
(node:414) UnhandledPromiseRejectionWarning: Error: /var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

    at Promise.all.then.arr (/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/exec-buffer/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:414) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:414) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:414) UnhandledPromiseRejectionWarning: Error: /var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
    at Promise.all.then.arr (/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/exec-buffer/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:414) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:414) UnhandledPromiseRejectionWarning: Error: /var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

    at Promise.all.then.arr (/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/exec-buffer/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:414) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by alifr** [comment]
Updating imagemin packages seems to fix the issue. I'll create a PR.

**Comment by BrendanBeltzNIH** [comment]
We're going to remove the image minification process after launch

**Comment by bryanpizzillo** [comment]
Closing this issue, mostly because the container now has all the right things to build. Thanks M1 macs! See #3579
