### ISSUE TITLE
Twig error on caregiver-support page

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#2111]
While waiting for a PDQ push to ODE 210 for migration testing, I noticed a twig failure in the Drupal watchdog logs.

Location: http://ncigovcdode210.prod.acquia-sites.com/about-cancer/coping/caregiver-support

Date: Thursday, June 27, 2019 - 18:47

Referrer: http://ncigovcdode210.prod.acquia-sites.com/types/bladder

User: Anonymous (not verified)

Severity: Notice

Hostname: 156.40.252.4

Message:

```
Notice: Undefined offset: 0 in Drupal\cgov_core\CgovCoreTwigExtensions->hasContent() (line 88 of /mnt/www/html/ncigovcdode210/docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php) #0 /mnt/www/html/ncigovcdode210/docroot/core/includes/bootstrap.inc(587): _drupal_error_handler_real(8, 'Undefined offse...', '/mnt/www/html/n...', 88, Array) #1 /mnt/www/html/ncigovcdode210/docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php(88): _drupal_error_handler(8, 'Undefined offse...', '/mnt/www/html/n...', 88, Array) #2 /mnt/tmp/ncigovcdode210/php_storage/twig/twig/5d1526fe8eecf_image_macros.twig_WE6m7rR68C9cwjhchUpKTco-W/PmmW--culUDB8YJi5Qp-bBywYyXkkZQHt6KIzrtSKcM.php(134): Drupal\cgov_core\CgovCoreTwigExtensions->hasContent(Array) #3 /mnt/tmp/ncigovcdode210/php_storage/twig/twig/5d1526fe8eecf_media--cgov-image--image-_W7DjDMMwM8fzncljGUYn7xKx3/K1KtaPtw11hDvenDZw4Q1zNXrvtYYPyjA0O5oRRYNnA.php(74): __TwigTemplate_d75e25f1bdc3a878d899a64cf5844ed313964b278f9830cbcaed66503d23efca->getarticleImage('image-medium', Array, NULL, Array, Array) #4 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(443): __TwigTemplate_7a2db226bb506fbdeea09945874db4fb2081aa92893185ef6db719550a3c87bf->doDisplay(Array, Array) #5 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array) #6 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(422): Twig\Template->display(Array) #7 /mnt/www/html/ncigovcdode210/docroot/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array) #8 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/custom...', Array) #9 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('media', Array) #10 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #11 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array) #12 /mnt/tmp/ncigovcdode210/php_storage/twig/twig/5d1526fe8eecf_field--field-image-articl_SDWRm4_ilVljhTKKmERSrCbto/jFOGHCDgNjseEJkZ4_-nlsLo3Kw3Dg5ZqE4KfWYnoEY.php(63): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true) #13 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(443): __TwigTemplate_b51dd22bf0ce4e4e9925169b4da6f58990bb4f599edf8f1920611f61f8ec5762->doDisplay(Array, Array) #14 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array) #15 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(422): Twig\Template->display(Array) #16 /mnt/www/html/ncigovcdode210/docroot/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array) #17 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/custom...', Array) #18 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('field', Array) #19 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #20 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array) #21 /mnt/tmp/ncigovcdode210/php_storage/twig/twig/5d1526fe8eecf_node--cgov-article--full._J5arCYhmyvGjXUHrDvCNAF3lF/DVTyJxWl7j699qAwzps5BbfUuH-HsJKvhQl7U9XspaY.php(77): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true) #22 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(443): __TwigTemplate_a283d1b5f39f2ae399bdbadc30aa0814ef5bf763cfdf0b6a3c3a45fee22019b1->doDisplay(Array, Array) #23 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array) #24 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(422): Twig\Template->display(Array) #25 /mnt/www/html/ncigovcdode210/docroot/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array) #26 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/custom...', Array) #27 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('node', Array) #28 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #29 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\Core\Render\Renderer->render(Array, false) #30 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() #31 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #32 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #33 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #34 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #35 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #36 /mnt/www/html/ncigovcdode210/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent)) #37 /mnt/www/html/ncigovcdode210/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #38 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #40 /mnt/www/html/ncigovcdode210/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #41 /mnt/www/html/ncigovcdode210/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true) #42 /mnt/www/html/ncigovcdode210/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true) #43 /mnt/www/html/ncigovcdode210/docroot/modules/contrib/shield/src/ShieldMiddleware.php(84): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #44 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #45 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #46 /mnt/www/html/ncigovcdode210/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #47 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #48 /mnt/www/html/ncigovcdode210/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #49 {main}.
```

**Comment by bkline** [comment]
Here's the message (wouldn't display correctly in the basic description):

[2111.log](https://github.com/NCIOCPL/cgov-digital-platform/files/3336924/2111.log)

**Comment by bkline** [comment]
Looks like the watchdog log mangles the formatting. Here's the log entry fixed by hand to be a little more readable.

```
Notice: Undefined offset: 0 in Drupal\cgov_core\CgovCoreTwigExtensions->hasContent() (line 88 of /mnt/www/html/ncigovcdode210/docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php)
#0 /mnt/www/html/ncigovcdode210/docroot/core/includes/bootstrap.inc(587): _drupal_error_handler_real(8, 'Undefined offse...', '/mnt/www/html/n...', 88, Array)
#1 /mnt/www/html/ncigovcdode210/docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php(88): _drupal_error_handler(8, 'Undefined offse...', '/mnt/www/html/n...', 88, Array)
#2 /mnt/tmp/ncigovcdode210/php_storage/twig/twig/5d1526fe8eecf_image_macros.twig_WE6m7rR68C9cwjhchUpKTco-W/PmmW--culUDB8YJi5Qp-bBywYyXkkZQHt6KIzrtSKcM.php(134): Drupal\cgov_core\CgovCoreTwigExtensions->hasContent(Array)
#3 /mnt/tmp/ncigovcdode210/php_storage/twig/twig/5d1526fe8eecf_media--cgov-image--image-_W7DjDMMwM8fzncljGUYn7xKx3/K1KtaPtw11hDvenDZw4Q1zNXrvtYYPyjA0O5oRRYNnA.php(74): __TwigTemplate_d75e25f1bdc3a878d899a64cf5844ed313964b278f9830cbcaed66503d23efca->getarticleImage('image-medium', Array, NULL, Array, Array)
#4 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(443): __TwigTemplate_7a2db226bb506fbdeea09945874db4fb2081aa92893185ef6db719550a3c87bf->doDisplay(Array, Array)
#5 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(422): Twig\Template->display(Array)
#7 /mnt/www/html/ncigovcdode210/docroot/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#8 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/custom...', Array)
#9 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('media', Array)
#10 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#11 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array)
#12 /mnt/tmp/ncigovcdode210/php_storage/twig/twig/5d1526fe8eecf_field--field-image-articl_SDWRm4_ilVljhTKKmERSrCbto/jFOGHCDgNjseEJkZ4_-nlsLo3Kw3Dg5ZqE4KfWYnoEY.php(63): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#13 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(443): __TwigTemplate_b51dd22bf0ce4e4e9925169b4da6f58990bb4f599edf8f1920611f61f8ec5762->doDisplay(Array, Array)
#14 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(422): Twig\Template->display(Array)
#16 /mnt/www/html/ncigovcdode210/docroot/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#17 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/custom...', Array)
#18 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('field', Array)
#19 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#20 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array)
#21 /mnt/tmp/ncigovcdode210/php_storage/twig/twig/5d1526fe8eecf_node--cgov-article--full._J5arCYhmyvGjXUHrDvCNAF3lF/DVTyJxWl7j699qAwzps5BbfUuH-HsJKvhQl7U9XspaY.php(77): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#22 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(443): __TwigTemplate_a283d1b5f39f2ae399bdbadc30aa0814ef5bf763cfdf0b6a3c3a45fee22019b1->doDisplay(Array, Array)
#23 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /mnt/www/html/ncigovcdode210/vendor/twig/twig/src/Template.php(422): Twig\Template->display(Array)
#25 /mnt/www/html/ncigovcdode210/docroot/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#26 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/custom...', Array)
#27 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('node', Array)
#28 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#29 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\Core\Render\Renderer->render(Array, false)
#30 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#31 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#32 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#33 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#34 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#35 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#36 /mnt/www/html/ncigovcdode210/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent))
#37 /mnt/www/html/ncigovcdode210/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#38 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#39 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#40 /mnt/www/html/ncigovcdode210/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#41 /mnt/www/html/ncigovcdode210/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#42 /mnt/www/html/ncigovcdode210/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#43 /mnt/www/html/ncigovcdode210/docroot/modules/contrib/shield/src/ShieldMiddleware.php(84): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#44 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#45 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#46 /mnt/www/html/ncigovcdode210/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#47 /mnt/www/html/ncigovcdode210/docroot/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#48 /mnt/www/html/ncigovcdode210/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#49 {main}.
```

**Comment by welshja** [comment]
Closing as outdated.
