### ISSUE TITLE
Cannot add updated r4r-app need to update web Dockerfile 

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2521]
This failed with the error below: `npm install --save git+https://github.com/NCIOCPL/r4r-app.git#0.1.7`

I tried the following:
* Update npm to npm 10 `npm install -g npm`
* `apt-get update` && `apt-get install build-essential`

## What to do:
1. update npm in the container
2. add the build-essential package.

npm WARN deprecated react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated core-js@2.5.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> weak-napi@1.0.3 install /var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/weak-napi
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/local/nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/local/nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/local/nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/nvm/versions/node/v10.14.1/bin/node" "/usr/local/nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/node_modules/weak-napi
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@15.2.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN cgov@1.0.0 No description
npm WARN cgov@1.0.0 No repository field.

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-25T00_41_14_684Z-debug.log
root@116bf3cd8141:/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov#

**Comment by bryanpizzillo** [comment]
This was completed a while ago in PR #2524. Oddly enough the pipelines file was not updated and we just ran into an issue there. Closing this though.
