### ISSUE TITLE
ODE deployments fail with a PHP error.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2746]
### Issue description
When deploying to an ODE, the deployment fails in the step
`blt cgov:user:load-all -D cgov.drupal_users_file=$users_file -D drush.ansi=false`

The error occurs because `blt/src/Commands/UsersCommand.php` has the possibility of throwing `BltException`, but there is no `use` statement or other declaration for the type.  The code file has not changed in 15 months.

> **ESTIMATE** XX

### Steps to reproduce the issue

1.  Create a new ODE.
2. Deploy build `pipelines-build-hotfix/v1.1.16`

### What's the expected result?
- Successful deployment

### What's the actual result?
- The deployment task

### Additional details / screenshot
```
## Load our test users.
blt cgov:user:load-all -D cgov.drupal_users_file=$users_file -D drush.ansi=false
PHP Fatal error:  Uncaught Error: Class 'Acquia\Blt\Custom\Commands\BltException' not found in /mnt/www/html/ncigovcdode332/blt/src/Commands/UsersCommand.php:25
Stack trace:
#0 [internal function]: Acquia\Blt\Custom\Commands\UsersCommand->loadUsers(Array)
#1 /mnt/www/html/ncigovcdode332/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#2 /mnt/www/html/ncigovcdode332/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /mnt/www/html/ncigovcdode332/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /mnt/www/html/ncigovcdode332/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component in /mnt/www/html/ncigovcdode332/blt/src/Commands/UsersCommand.php on line 25
[2020-04-06 22:39:31] Command returned exit code 255: /mnt/users/ncigovcd/ode332.shell /var/www/html/ncigovcd.ode332/hooks/common/post-code-update/post-code-update.sh ncigovcd ode332 pipelines-build-hotfix/v1.1.16 pipelines-build-hotfix/v1.1.16 ncigovcd@svn-29892.prod.hosting.acquia.com:ncigovcd.git git executing hook post-code-update
[2020-04-06 22:39:31] Finished hook: post-code-update
```

**Comment by blairlearn** [comment]
The error is triggered by missing data files, the missing class declaration causes the error message to be hidden.
