### ISSUE TITLE
Cannot Regenerate URLs in Bulk

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2814]
### Issue description
We cannot regenerate URLs in Bulk using the UI. This affects our ability to easily rebuild URLs when site sections are moved around. While this option is not exposed to site admins on production, it is desired based on some large scale moves. This underlying issue prevents that from being a possibility. (This request is actually issue #2784)

> **ESTIMATE** NN

### Steps to reproduce the issue

1.  Login as the admin account (ACSF confirmed to break)
2.  Go to `/admin/config/search/path/update_bulk`
3. Select Media and Content from the Types list
4. Select Regenerate URL aliases for all paths
5. Click update

The batch processing will start and at some point you will see the following error on screen:
![image](https://user-images.githubusercontent.com/11215649/85422418-970efe80-b543-11ea-82d6-285e169338d1.png)

Digging into the backend logs, there are three errors from the batch route generating the on-screen ajax error. Those are attached below. However, it looks like from the third entry that the root cause is `Call to a member function get() on null in cgov_site_section_tokens()`.

**Error Messages**
```
drupal-watchdog staging-3324 Jun 23 15:12:51 staging-3324 ncigov01test[31543]: https://www-cms-test.cancer.gov|1592925171|php|23.46.238.110|https://www-cms-test.cancer.gov/batch?id=1106&op=finished|https://www-cms-test.cancer.gov/batch?id=1106&op=start|1||Warning: Illegal offset type in Symfony\Component\HttpFoundation\Session\Flash\FlashBag->add() (line 59 of /mnt/www/html/ncigov01test/vendor/symfony/http-foundation/Session/Flash/FlashBag.php) #0 /mnt/www/html/ncigov01test/docroot/core/includes/bootstrap.inc(587): _drupal_error_handler_real(2, 'Illegal offset ...', '/mnt/www/html/n...', 59, Array) #1 /mnt/www/html/ncigov01test/vendor/symfony/http-foundation/Session/Flash/FlashBag.php(59): _drupal_error_handler(2, 'Illegal offset ...', '/mnt/www/html/n...', 59, Array) #2 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/Messenger/Messenger.php(60): Symfony\Component\HttpFoundation\Session\Flash\FlashBag->add(Array, Object(Drupal\Core\Render\Markup)) #3 /mnt/www/html/ncigov01test/docroot/modules/contrib/pathauto/src/Form/PathautoBulkUpdateForm.php(180): Drupal\Core\Messenger\Messenger->addMessage(Object(Drupal\Core\Render\Markup), Array) #4 /mnt/www/html/ncigov01test/docroot/core/includes/batch.inc(454): Drupal\pathauto\Form\PathautoBulkUpdateForm::batchFinished(false, Array, Array, '2 sec') #5 /mnt/www/html/ncigov01test/docroot/core/includes/batch.inc(98): _batch_finished() #6 /mnt/www/html/ncigov01test/docroot/core/modules/system/src/Controller/BatchController.php(55): _batch_page(Object(Symfony\Component\HttpFoundation\Request)) #7 [internal function]: Drupal\system\Controller\BatchController->batchPage(Object(Symfony\Component\HttpFoundation\Request)) #8 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #9 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #10 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #11 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #12 /mnt/www/html/ncigov01test/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #13 /mnt/www/html/ncigov01test/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #14 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #15 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #16 /mnt/www/html/ncigov01test/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /mnt/www/html/ncigov01test/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /mnt/www/html/ncigov01test/docroot/modules/contrib/shield/src/ShieldMiddleware.php(84): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /mnt/www/html/ncigov01test/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /mnt/www/html/ncigov01test/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #24 {main}. request_id="v-01939426-b564-11ea-ad87-0719343edfa4"Close
```
```
drupal-watchdog staging-3324 Jun 23 15:12:51 staging-3324 ncigov01test[31543]: https://www-cms-test.cancer.gov|1592925171|php|23.46.238.110|https://www-cms-test.cancer.gov/batch?id=1106&op=finished|https://www-cms-test.cancer.gov/batch?id=1106&op=start|1||Warning: array_key_exists(): The first argument should be either a string or an integer in Symfony\Component\HttpFoundation\Session\Flash\FlashBag->has() (line 126 of /mnt/www/html/ncigov01test/vendor/symfony/http-foundation/Session/Flash/FlashBag.php) #0 /mnt/www/html/ncigov01test/docroot/core/includes/bootstrap.inc(587): _drupal_error_handler_real(2, 'array_key_exist...', '/mnt/www/html/n...', 126, Array) #1 [internal function]: _drupal_error_handler(2, 'array_key_exist...', '/mnt/www/html/n...', 126, Array) #2 /mnt/www/html/ncigov01test/vendor/symfony/http-foundation/Session/Flash/FlashBag.php(126): array_key_exists(Array, Array) #3 /mnt/www/html/ncigov01test/vendor/symfony/http-foundation/Session/Flash/FlashBag.php(67): Symfony\Component\HttpFoundation\Session\Flash\FlashBag->has(Array) #4 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/Messenger/Messenger.php(59): Symfony\Component\HttpFoundation\Session\Flash\FlashBag->peek(Array) #5 /mnt/www/html/ncigov01test/docroot/modules/contrib/pathauto/src/Form/PathautoBulkUpdateForm.php(180): Drupal\Core\Messenger\Messenger->addMessage(Object(Drupal\Core\Render\Markup), Array) #6 /mnt/www/html/ncigov01test/docroot/core/includes/batch.inc(454): Drupal\pathauto\Form\PathautoBulkUpdateForm::batchFinished(false, Array, Array, '2 sec') #7 /mnt/www/html/ncigov01test/docroot/core/includes/batch.inc(98): _batch_finished() #8 /mnt/www/html/ncigov01test/docroot/core/modules/system/src/Controller/BatchController.php(55): _batch_page(Object(Symfony\Component\HttpFoundation\Request)) #9 [internal function]: Drupal\system\Controller\BatchController->batchPage(Object(Symfony\Component\HttpFoundation\Request)) #10 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #11 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #12 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #13 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #14 /mnt/www/html/ncigov01test/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #15 /mnt/www/html/ncigov01test/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #16 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /mnt/www/html/ncigov01test/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /mnt/www/html/ncigov01test/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /mnt/www/html/ncigov01test/docroot/modules/contrib/shield/src/ShieldMiddleware.php(84): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /mnt/www/html/ncigov01test/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /mnt/www/html/ncigov01test/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #26 {main}. request_id="v-01939426-b564-11ea-ad87-0719343edfa4"Close
```
```
drupal-watchdog staging-3324 Jun 23 15:12:48 staging-3324 ncigov01test[31543]: https://www-cms-test.cancer.gov|1592925168|php|23.46.238.110|https://www-cms-test.cancer.gov/batch?_format=json&id=1106&op=do&op=do_nojs|https://www-cms-test.cancer.gov/batch?id=1106&op=start|1||Error: Call to a member function get() on null in cgov_site_section_tokens() (line 62 of /mnt/www/html/ncigov01test/docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc) #0 [internal function]: cgov_site_section_tokens('cgov_tokens', Array, Array, Array, Object(Drupal\Core\Render\BubbleableMetadata)) #1 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('cgov_site_secti...', Array) #2 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/Utility/Token.php(304): Drupal\Core\Extension\ModuleHandler->invokeAll('tokens', Array) #3 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/Utility/Token.php(196): Drupal\Core\Utility\Token->generate('cgov_tokens', Array, Array, Array, Object(Drupal\Core\Render\BubbleableMetadata)) #4 /mnt/www/html/ncigov01test/docroot/modules/contrib/pathauto/src/PathautoGenerator.php(228): Drupal\Core\Utility\Token->replace('/[cgov_tokens:c...', Array, Array, Object(Drupal\Core\Render\BubbleableMetadata)) #5 /mnt/www/html/ncigov01test/docroot/modules/contrib/pathauto/src/PathautoGenerator.php(380): Drupal\pathauto\PathautoGenerator->createEntityAlias(Object(Drupal\media\Entity\Media), 'bulkupdate') #6 /mnt/www/html/ncigov01test/docroot/modules/contrib/pathauto/src/Plugin/pathauto/AliasType/EntityAliasTypeBase.php(275): Drupal\pathauto\PathautoGenerator->updateEntityAlias(Object(Drupal\media\Entity\Media), 'bulkupdate', Array) #7 /mnt/www/html/ncigov01test/docroot/modules/contrib/pathauto/src/Plugin/pathauto/AliasType/EntityAliasTypeBase.php(189): Drupal\pathauto\Plugin\pathauto\AliasType\EntityAliasTypeBase->bulkUpdate(Array) #8 /mnt/www/html/ncigov01test/docroot/modules/contrib/pathauto/src/Form/PathautoBulkUpdateForm.php(158): Drupal\pathauto\Plugin\pathauto\AliasType\EntityAliasTypeBase->batchUpdate('all', Array) #9 /mnt/www/html/ncigov01test/docroot/core/includes/batch.inc(295): Drupal\pathauto\Form\PathautoBulkUpdateForm::batchProcess('canonical_entit...', 'all', Array) #10 /mnt/www/html/ncigov01test/docroot/core/includes/batch.inc(137): _batch_process() #11 /mnt/www/html/ncigov01test/docroot/core/includes/batch.inc(93): _batch_do() #12 /mnt/www/html/ncigov01test/docroot/core/modules/system/src/Controller/BatchController.php(55): _batch_page(Object(Symfony\Component\HttpFoundation\Request)) #13 [internal function]: Drupal\system\Controller\BatchController->batchPage(Object(Symfony\Component\HttpFoundation\Request)) #14 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #15 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #16 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #17 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #18 /mnt/www/html/ncigov01test/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #19 /mnt/www/html/ncigov01test/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #20 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /mnt/www/html/ncigov01test/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /mnt/www/html/ncigov01test/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /mnt/www/html/ncigov01test/docroot/modules/contrib/shield/src/ShieldMiddleware.php(84): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /mnt/www/html/ncigov01test/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #28 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /mnt/www/html/ncigov01test/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #30 {main}. request_id="v-ff762618-b563-11ea-a8a1-bbe7e6e065db"
```

**Comment by bryanpizzillo** [comment]
Additional Notes:
The YAML content we load does not have any issues, so it looks like this may be an issue with the cgov content. (Which should make it super fun to find)
