### ISSUE TITLE
Spike: Investigate JSON:API

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3223]
## In order to share raw content for NCIDS prototyping, the JSON:API module needs to be enabled in drupal to serve up all content as JSON.
> **Estimated Timeframe** *# of days for completion* 

### Expected Deliverables:
* A working prototype
* A set of steps/tasks needed for enabling the module.

### Additional Notes:
* This was prototyped back in Nov of last year, and we have since updated to Drupal 9.2, so the content and codebase are very out of date.
* The prototype is in use by the NCIDS team for prototyping with Gatsby.
* The current prototype has no ticket to hold notes, so this is a place for that.

**Comment by bryanpizzillo** [comment]
Some work was done on an initial prototype branch:
## Setup Image Styles
1. Added `consumer_image_styles`, `consumers` and `jsonapi_extras` modules.
2. Added install hook to `cgov_image` to add the styles to the "default" consumer. 
    ```
    $image_tools = \Drupal::service('cgov_image.image_tools');
    $image_tools->addImageStylesToDefaultConsumer();
    ```
3. Added update hook to turn it on for existing sites. (Same code)
4. Added a `jsonapi_extras.jsonapi_resource_config` [file](https://github.com/NCIOCPL/cgov-digital-platform/blob/e1f6c4d8137d0536e7f83e6dd143b72463e693d0/docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/jsonapi_extras.jsonapi_resource_config.media--cgov_image.yml) for `cgov_image`
5. Updated `CgovImageTools.php` to [add the helper that adds in the image styles](https://github.com/NCIOCPL/cgov-digital-platform/blob/e1f6c4d8137d0536e7f83e6dd143b72463e693d0/docroot/profiles/custom/cgov_site/modules/custom/cgov_image/src/CgovImageTools.php#L43) to the default consumer.

The last commit for the old prototype branch was [cabcbc8](https://github.com/NCIOCPL/cgov-digital-platform/commit/cabcbc8b114774dab7e8bcb03279fef66f38a5e0)

**Comment by bryanpizzillo** [comment]
Here is a new finding. A backup of www was working perfectly fine on an ODE. I then staged a number of sites to ACSF about 2 weeks after that backup. Running the same Gatsby process to ingest the content, I am now getting an error for www. 
There are multiple URLs this is failing for, however the error seems to be the same. 

Some differences for the future debugging:
* ODEs do not have memcache enabled anymore, where as they are enabled in ACSF environments.
* ACSF is fronted by Akamai, where as ODEs are not.
   * Using the acsitefactory name, **IT DOES WORK**. So this would indicate there is something in Akamai that is messing with the request. 

```
Notice: unserialize(): Error at offset 0 of 8 bytes in Drupal\serialization\Normalizer\PrimitiveDataNormalizer->normalize() (line 26 of /mnt/www/html/ncigov01test/docroot/core/modules/serialization/src/Normalizer/PrimitiveDataNormalizer.php)
#0 /mnt/www/html/ncigov01test/docroot/core/includes/bootstrap.inc(164): _drupal_error_handler_real(8, 'unserialize(): ...', '/mnt/www/html/n...', 26)
#1 [internal function]: _drupal_error_handler(8, 'unserialize(): ...', '/mnt/www/html/n...', 26)
#2 /mnt/www/html/ncigov01test/docroot/core/modules/serialization/src/Normalizer/PrimitiveDataNormalizer.php(26): unserialize('web_page')
#3 /mnt/www/html/ncigov01test/vendor/symfony/serializer/Serializer.php(159): Drupal\serialization\Normalizer\PrimitiveDataNormalizer->normalize(Object(Drupal\Core\TypedData\Plugin\DataType\StringData), 'api_json', Array)
#4 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Serializer/Serializer.php(65): Symfony\Component\Serializer\Serializer->normalize(Object(Drupal\Core\TypedData\Plugin\DataType\StringData), 'api_json', Array)
#5 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Normalizer/FieldItemNormalizer.php(67): Drupal\jsonapi\Serializer\Serializer->normalize(Object(Drupal\Core\TypedData\Plugin\DataType\StringData), 'api_json', Array)
#6 /mnt/www/html/ncigov01test/vendor/symfony/serializer/Serializer.php(159): Drupal\jsonapi\Normalizer\FieldItemNormalizer->normalize(Object(Drupal\cgov_schema_org\Plugin\Field\FieldType\CgovSchemaOrgFieldItem), 'api_json', Array)
#7 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Serializer/Serializer.php(62): Symfony\Component\Serializer\Serializer->normalize(Object(Drupal\cgov_schema_org\Plugin\Field\FieldType\CgovSchemaOrgFieldItem), 'api_json', Array)
#8 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Normalizer/FieldNormalizer.php(86): Drupal\jsonapi\Serializer\Serializer->normalize(Object(Drupal\cgov_schema_org\Plugin\Field\FieldType\CgovSchemaOrgFieldItem), 'api_json', Array)
#9 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Normalizer/FieldNormalizer.php(28): Drupal\jsonapi\Normalizer\FieldNormalizer->normalizeFieldItems(Object(Drupal\Core\Field\FieldItemList), 'api_json', Array)
#10 /mnt/www/html/ncigov01test/vendor/symfony/serializer/Serializer.php(159): Drupal\jsonapi\Normalizer\FieldNormalizer->normalize(Object(Drupal\Core\Field\FieldItemList), 'api_json', Array)
#11 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Serializer/Serializer.php(62): Symfony\Component\Serializer\Serializer->normalize(Object(Drupal\Core\Field\FieldItemList), 'api_json', Array)
#12 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Normalizer/ResourceObjectNormalizer.php(181): Drupal\jsonapi\Serializer\Serializer->normalize(Object(Drupal\Core\Field\FieldItemList), 'api_json', Array)
#13 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Normalizer/ResourceObjectNormalizer.php(116): Drupal\jsonapi\Normalizer\ResourceObjectNormalizer->serializeField(Object(Drupal\Core\Field\FieldItemList), Array, 'api_json')
#14 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Normalizer/ResourceObjectNormalizer.php(68): Drupal\jsonapi\Normalizer\ResourceObjectNormalizer->getNormalization(Array, Object(Drupal\jsonapi\JsonApiResource\ResourceObject), 'api_json', Array)
#15 /mnt/www/html/ncigov01test/vendor/symfony/serializer/Serializer.php(159): Drupal\jsonapi\Normalizer\ResourceObjectNormalizer->normalize(Object(Drupal\jsonapi\JsonApiResource\ResourceObject), 'api_json', Array)
#16 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Serializer/Serializer.php(62): Symfony\Component\Serializer\Serializer->normalize(Object(Drupal\jsonapi\JsonApiResource\ResourceObject), 'api_json', Array)
#17 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Normalizer/DataNormalizer.php(21): Drupal\jsonapi\Serializer\Serializer->normalize(Object(Drupal\jsonapi\JsonApiResource\ResourceObject), 'api_json', Array)
#18 [internal function]: Drupal\jsonapi\Normalizer\DataNormalizer->Drupal\jsonapi\Normalizer\{closure}(Object(Drupal\jsonapi\JsonApiResource\ResourceObject))
#19 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Normalizer/DataNormalizer.php(22): array_map(Object(Closure), Array)
#20 /mnt/www/html/ncigov01test/vendor/symfony/serializer/Serializer.php(159): Drupal\jsonapi\Normalizer\DataNormalizer->normalize(Object(Drupal\jsonapi\JsonApiResource\ResourceObjectData), 'api_json', Array)
#21 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Serializer/Serializer.php(62): Symfony\Component\Serializer\Serializer->normalize(Object(Drupal\jsonapi\JsonApiResource\ResourceObjectData), 'api_json', Array)
#22 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Normalizer/JsonApiDocumentTopLevelNormalizer.php(188): Drupal\jsonapi\Serializer\Serializer->normalize(Object(Drupal\jsonapi\JsonApiResource\ResourceObjectData), 'api_json', Array)
#23 /mnt/www/html/ncigov01test/vendor/symfony/serializer/Serializer.php(159): Drupal\jsonapi\Normalizer\JsonApiDocumentTopLevelNormalizer->normalize(Object(Drupal\jsonapi\JsonApiResource\JsonApiDocumentTopLevel), 'api_json', Array)
#24 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/Serializer/Serializer.php(62): Symfony\Component\Serializer\Serializer->normalize(Object(Drupal\jsonapi\JsonApiResource\JsonApiDocumentTopLevel), 'api_json', Array)
#25 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/EventSubscriber/ResourceResponseSubscriber.php(120): Drupal\jsonapi\Serializer\Serializer->normalize(Object(Drupal\jsonapi\JsonApiResource\JsonApiDocumentTopLevel), 'api_json', Array)
#26 /mnt/www/html/ncigov01test/docroot/core/modules/jsonapi/src/EventSubscriber/ResourceResponseSubscriber.php(85): Drupal\jsonapi\EventSubscriber\ResourceResponseSubscriber->renderResponseBody(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\jsonapi\CacheableResourceResponse), Object(Drupal\jsonapi\Serializer\Serializer), 'api_json')
#27 [internal function]: Drupal\jsonapi\EventSubscriber\ResourceResponseSubscriber->onResponse(Object(Symfony\Component\HttpKernel\Event\ResponseEvent), 'kernel.response', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#28 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\ResponseEvent), 'kernel.response', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#29 /mnt/www/html/ncigov01test/vendor/symfony/http-kernel/HttpKernel.php(214): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ResponseEvent), 'kernel.response')
#30 /mnt/www/html/ncigov01test/vendor/symfony/http-kernel/HttpKernel.php(202): Symfony\Component\HttpKernel\HttpKernel->filterResponse(Object(Drupal\jsonapi\CacheableResourceResponse), Object(Symfony\Component\HttpFoundation\Request), 1)
#31 /mnt/www/html/ncigov01test/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#32 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#33 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#34 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#35 /mnt/www/html/ncigov01test/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#36 /mnt/www/html/ncigov01test/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#37 /mnt/www/html/ncigov01test/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#38 /mnt/www/html/ncigov01test/docroot/modules/contrib/shield/src/ShieldMiddleware.php(263): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#39 /mnt/www/html/ncigov01test/docroot/modules/contrib/shield/src/ShieldMiddleware.php(130): Drupal\shield\ShieldMiddleware->bypass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#40 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#41 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#42 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#43 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#44 /mnt/www/html/ncigov01test/docroot/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#45 /mnt/www/html/ncigov01test/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#46 {main}
```

**Comment by welshja** [comment]
Closing as this was investigated as we looked at NCIDS and how to migrate.
