### ISSUE TITLE
Blog entry lookup not validating inputs

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3364]
### Issue description
Security scans result in watchdog entries because of an attempt to pass a string into the php `mktime` function.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Browse to a page of blog entries with an invalid month input.  e.g. https://www.cancer.gov/news-events/cancer-currents-blog?month=http%3A%2F%2Fmetadata.google.internal%2FcomputeMetadata%2Fv1beta1%2Finstance%2Fsecurity-scanner%2Fc%2F27471154270720000091302911n&year=2016
2. Observe the returned page and HTTP status.
3. Examine the watchdog log

### What's the expected result?
- No watchdog entries
- Probably a status 400 return

### What's the actual result?
- A page showing no entries
- A watchdog entry: `Warning: mktime() expects parameter 4 to be int, string given`

### Additional details / screenshot

The log entry happens because [BlogManager:: getBlogSeriesTitle](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php#L402) assumes `month` is a valid month.

In addition to validating here, there should also be validation at a higher level to prevent trying to look up blog entries for an invalid month.

**Full log entry**
```
https://www.cancer.gov|1650455559|php|184.30.43.150|https://www.cancer.gov/news-events/cancer-currents-blog?month=http%3A%2F%2Fmetadata.google.internal%2FcomputeMetadata%2Fv1beta1%2Finstance%2Fsecurity-scanner%2Fc%2F27471154270720000091302911n&year=2016||0||Warning: mktime() expects parameter 4 to be int, string given in Drupal\cgov_blog\Services\BlogManager->getBlogSeriesTitle() (line 408 of /mnt/www/html/ncigov01live/docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php) #0 /mnt/www/html/ncigov01live/docroot/core/includes/bootstrap.inc(312): _drupal_error_handler_real(2, 'mktime() expect...', '/mnt/www/html/n...', 408)
#1 [internal function]: _drupal_error_handler(2, 'mktime() expect...', '/mnt/www/html/n...', 408, Array)
#2 /mnt/www/html/ncigov01live/docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php(408): mktime(0, 0, 0, 'http://metadata...', 10)
#3 /mnt/www/html/ncigov01live/docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/CgovBlogTwigExtensions.php(58): Drupal\cgov_blog\Services\BlogManager->getBlogSeriesTitle('http://metadata...', '2016', '', Object(Drupal\node\Entity\Node))
#4 /mnt/tmp/ncigov01live/php_storage/twig/043a1cb/xnrzdm211/twig/6258ce183dbfa_blog_macros.twig_Mq99r_C52XobRLywu3q1qAn7e/pZwDv2kz8otGVVN0h69_EZrQ4FjiKb9QSTsG3fkN_2s.php(261): Drupal\cgov_blog\CgovBlogTwigExtensions->getBlogSeriesTitle('http://metadata...', '2016', '', Object(Drupal\node\Entity\Node))
#5 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Extension/CoreExtension.php(1169): __TwigTemplate_ed96c9291bb0d2e7c6bef495356b7016a25b5f8307074e3ce6982dde1c0cc72b->macro_drawBlogSeriesTitle('http://metadata...', '2016', '', Object(Drupal\node\Entity\Node))
#6 /mnt/tmp/ncigov01live/php_storage/twig/043a1cb/xnrzdm211/twig/6258ce183dbfa_node--cgov-blog-series--f_hQ61sF5U1cNUcMN5jcZeca3or/JElhVwTEu8i3LY8LSP0hnuM3McD506R-9UjbJNRbO_4.php(70): twig_call_macro(Object(__TwigTemplate_ed96c9291bb0d2e7c6bef495356b7016a25b5f8307074e3ce6982dde1c0cc72b), 'macro_drawBlogS...', Array, 17, Array, Object(Twig\Source))
#7 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(405): __TwigTemplate_1a00b761f937844c1ebede81b86801b33624f21e6d63db0c32ae051af81b3776->doDisplay(Array, Array)
#8 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#10 /mnt/www/html/ncigov01live/docroot/core/themes/engines/twig/twig.engine(65): Twig\Template->render(Array)
#11 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/custom...', Array)
#12 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/Renderer.php(436): Drupal\Core\Theme\ThemeManager->render('node', Array)
#13 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/Renderer.php(201): Drupal\Core\Render\Renderer->doRender(Array, false)
#14 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(450): Drupal\Core\Render\Renderer->render(Array)
#15 /mnt/tmp/ncigov01live/php_storage/twig/043a1cb/xnrzdm211/twig/6258ce183dbfa_block.html.twig_hHoA-nblXQZDtcOu94hnjbSd1/QL6qjvDJ-mKq15JA6X-SYQkhls8zUiDrAFaC5anfiOI.php(76): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#16 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(182): __TwigTemplate_e1da2bbe8c8b536520d87ad4f1dcefa9c68aea4266ba06d6a760f6096349a86e->block_content(Array, Array)
#17 /mnt/tmp/ncigov01live/php_storage/twig/043a1cb/xnrzdm211/twig/6258ce183dbfa_block.html.twig_hHoA-nblXQZDtcOu94hnjbSd1/QL6qjvDJ-mKq15JA6X-SYQkhls8zUiDrAFaC5anfiOI.php(64): Twig\Template->displayBlock('content', Array, Array)
#18 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e1da2bbe8c8b536520d87ad4f1dcefa9c68aea4266ba06d6a760f6096349a86e->doDisplay(Array, Array)
#19 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#21 /mnt/www/html/ncigov01live/docroot/core/themes/engines/twig/twig.engine(65): Twig\Template->render(Array)
#22 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/sta...', Array)
#23 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/Renderer.php(436): Drupal\Core\Theme\ThemeManager->render('block', Array)
#24 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/Renderer.php(449): Drupal\Core\Render\Renderer->doRender(Array)
#25 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/Renderer.php(201): Drupal\Core\Render\Renderer->doRender(Array, false)
#26 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(450): Drupal\Core\Render\Renderer->render(Array)
#27 /mnt/tmp/ncigov01live/php_storage/twig/043a1cb/xnrzdm211/twig/6258ce183dbfa_layout--cgov-blog.html.tw_cE7_c2fumOz1sJUtJwzeocyig/47KXNIpGyZ2A2GdP7TuulFg5AnH0Z2z0Y8jeMH-Ne50.php(44): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#28 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(405): __TwigTemplate_4258d600ef48d0017404909018c91d3c92121baeeaf3374879deb6994f841166->doDisplay(Array, Array)
#29 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#30 /mnt/www/html/ncigov01live/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#31 /mnt/www/html/ncigov01live/docroot/core/themes/engines/twig/twig.engine(65): Twig\Template->render(Array)
#32 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/custom...', Array)
#33 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/Renderer.php(436): Drupal\Core\Theme\ThemeManager->render('layout__cgov_bl...', Array)
#34 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/Renderer.php(201): Drupal\Core\Render\Renderer->doRender(Array, false)
#35 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(241): Drupal\Core\Render\Renderer->render(Array, false)
#36 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/Renderer.php(578): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#37 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(242): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#38 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(132): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#39 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#40 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#41 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#42 /mnt/www/html/ncigov01live/vendor/symfony/http-kernel/HttpKernel.php(163): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view')
#43 /mnt/www/html/ncigov01live/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#44 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#45 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#46 /mnt/www/html/ncigov01live/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#47 /mnt/www/html/ncigov01live/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#48 /mnt/www/html/ncigov01live/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#49 /mnt/www/html/ncigov01live/docroot/modules/contrib/shield/src/ShieldMiddleware.php(91): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#50 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#51 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#52 /mnt/www/html/ncigov01live/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#53 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/DrupalKernel.php(717): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#54 /mnt/www/html/ncigov01live/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#55 {main}. request_id="v-60078cbc-c0a0-11ec-877e-335233de18fc"
```

**Comment by blairlearn** [comment]
See comments on #3402 for an explanation of the problem.

**Comment by jfrank-nih** [comment]
Closing this as a dupe of #3402 as they are effectively the same.
