### ISSUE TITLE
There is an issue in unit tests with the footer

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3475]
### Issue description
> **ESTIMATE** TBD

The following stack trace is appearing during unit tests. This is possibly due to not awaiting some action trying to capture the form errors.

```
console.error
    Error: Uncaught [RangeError: Maximum call stack size exceeded]
        at reportException (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
        at invokeEventListeners (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLFormElementImpl._dispatch (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at fireAnEvent (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
        at HTMLFormElementImpl.submit (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:84:10)
        at HTMLFormElement.submit (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/jsdom/lib/jsdom/living/generated/HTMLFormElement.js:108:34)
        at NCISubscribe.handleSubmit (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/@nciocpl/ncids-js/lib/cjs/components/nci-subscribe/nci-subscribe.component.js:50:18)
        at HTMLFormElement.NCISubscribe.submitEventListener (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/@nciocpl/ncids-js/lib/cjs/components/nci-subscribe/nci-subscribe.component.js:7:48)
        at HTMLFormElement.callTheUserObjectsOperation (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30) RangeError: Maximum call stack size exceeded
        at Object.<anonymous> (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/react-is/cjs/react-is.development.js:225:5)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/var/www/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/node_modules/react-is/index.js:6:20)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLFormElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
```

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed by PR #3508!
