### ISSUE TITLE
mozjpeg, called from gulp-imagemin, throws an error.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3579]
This one is pretty fun. So the version of imagemin-mozjpeg we use must be built from source to support ARM64. The decoded error message thrown by node is `qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory\n`. The thing is, if there is no build tools it tries to run the intel version, which dies. After installing the tools into the docker container, the current version we have builds and works ok.

So we actually need to install a number of things in the docker container in order to be able to build mozjpeg:
- autoconf
- libtool
- libpng-dev
- m4
- pkg-config
- nasm

**Comment by bryanpizzillo** [comment]
## Error Message:
```
[19:57:50] Using gulpfile /var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/gulpfile.js

[19:57:50] Starting 'default'...

[19:57:50] Starting 'clean'...

[19:57:50] Finished 'clean' after 51 ms

[19:57:50] Starting 'sprites'...

[19:57:50] Finished 'sprites' after 24 ms

[19:57:50] Starting 'variant_sprites'...

[19:57:50] Finished 'variant_sprites' after 11 ms

[19:57:50] Starting 'images'...

[19:57:50] Finished 'images' after 6.08 ms

[19:57:50] Finished 'default' after 95 ms



node:internal/process/promises:246

          triggerUncaughtException(err, true /* fromPromise */);

          ^

PluginError: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)

    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)

Emitted 'error' event on Domain instance at:

    at DestroyableTransform.emit (node:domain:525:12)

    at DestroyableTransform.onerror (/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:640:52)

    at DestroyableTransform.emit (node:events:390:28)

    at DestroyableTransform.emit (node:domain:475:12)

    at /var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/node_modules/through2-concurrent/through2-concurrent.js:41:14

    at /var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/node_modules/gulp-imagemin/index.js:98:5

    at processTicksAndRejections (node:internal/process/task_queues:96:5) {

  errno: -32,

  code: 'EPIPE',

  syscall: 'write',

  stdout: Buffer(0) [Uint8Array] [],

  stderr: Buffer(85) [Uint8Array] [

    113, 101, 109, 117,  45, 120,  56,  54,  95,  54,  52,  58,

     32,  67, 111, 117, 108, 100,  32, 110, 111, 116,  32, 111,

    112, 101, 110,  32,  39,  47, 108, 105,  98,  54,  52,  47,

    108, 100,  45, 108, 105, 110, 117, 120,  45, 120,  56,  54,

     45,  54,  52,  46, 115, 111,  46,  50,  39,  58,  32,  78,

    111,  32, 115, 117,  99, 104,  32, 102, 105, 108, 101,  32,

    111, 114,  32, 100, 105, 114, 101,  99, 116, 111, 114, 121,

     10

  ],

  failed: true,

  signal: null,

  cmd: '/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/node_modules/mozjpeg/vendor/cjpeg -quality 80',

  timedOut: false,

  killed: false,

  __safety: undefined,

  _stack: undefined,

  plugin: 'gulp-imagemin',

  showProperties: true,

  showStack: false,

  fileName: '/var/www/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/purple/assets/multimedia-background-purple.jpg',

  domainEmitter: DestroyableTransform {

    _readableState: ReadableState {

      objectMode: true,

      highWaterMark: 16,

      buffer: BufferList { head: null, tail: null, length: 0 },

      length: 0,

      pipes: Pumpify {

        _readableState: ReadableState {

          objectMode: true,

          highWaterMark: 16,

          buffer: BufferList { head: null, tail: null, length: 0 },

          length: 0,

          pipes: PassThrough {

            _readableState: [ReadableState],

            readable: true,

            _events: [Object: null prototype],

            _eventsCount: 7,

            _maxListeners: 0,

            _writableState: [WritableState],

            writable: true,

            allowHalfOpen: true,

            _transformState: [Object],

            add: [Function: add],

            isEmpty: [Function: isEmpty],

            [Symbol(kCapture)]: false

          },

          pipesCount: 1,

          flowing: true,

          ended: false,

          endEmitted: false,

          reading: true,

          sync: false,

          needReadable: true,

          emittedReadable: false,

          readableListening: false,

          resumeScheduled: false,

          destroyed: false,

          defaultEncoding: 'utf8',

          awaitDrain: 0,

          readingMore: false,

          decoder: null,

          encoding: null

        },

        readable: true,

        _events: [Object: null prototype] {

          end: [ [Function], [Function], [Function] ],

          close: [ [Function: onclose], [Function] ],

          prefinish: [Function (anonymous)],

          newListener: [Function: removeSink],

          removeListener: [ [Function: removeSink], [Function: addSink] ],

          unpipe: [Function: onunpipe],

          drain: [Function (anonymous)],

          error: [ [Function: onerror], [Function] ],

          finish: [Function: bound onceWrapper] {

            listener: [Function: onfinish]

          },

          data: [Function: ondata]

        },

        _eventsCount: 10,

        _maxListeners: undefined,

        _writableState: WritableState {

          objectMode: true,

          highWaterMark: 16,

          finalCalled: false,

          needDrain: false,

          ending: false,

          ended: false,

          finished: false,

          destroyed: false,

          decodeStrings: true,

          defaultEncoding: 'utf8',

          length: 0,

          writing: false,

          corked: 0,

          sync: true,

          bufferProcessing: false,

          onwrite: [Function (anonymous)],

          writecb: null,

          writelen: 0,

          bufferedRequest: null,

          lastBufferedRequest: null,

          pendingcb: 0,

          prefinished: false,

          errorEmitted: false,

          bufferedRequestCount: 0,

          corkedRequestsFree: CorkedRequest {

            next: null,

            entry: null,

            finish: [Function (anonymous)]

          }

        },

        writable: true,

        allowHalfOpen: true,

        _writable: DestroyableTransform {

          _readableState: ReadableState {

            objectMode: true,

            highWaterMark: 16,

            buffer: [BufferList],

            length: 0,

            pipes: [DestroyableTransform],

            pipesCount: 1,

            flowing: true,

            ended: false,

            endEmitted: false,

            reading: true,

            sync: false,

            needReadable: true,

            emittedReadable: false,

            readableListening: false,

            resumeScheduled: false,

            destroyed: false,

            defaultEncoding: 'utf8',

            awaitDrain: 0,

            readingMore: false,

            decoder: null,

            encoding: null

          },

          readable: true,

          _events: [Object: null prototype] {

            end: [Array],

            prefinish: [Function: prefinish],

            close: [Array],

            finish: [Array],

            error: [Array],

            data: [Function: ondata],

            drain: [Function: ondrain]

          },

          _eventsCount: 7,

          _maxListeners: undefined,

          _writableState: WritableState {

            objectMode: true,

            highWaterMark: 16,

            finalCalled: false,

            needDrain: false,

            ending: false,

            ended: false,

            finished: false,

            destroyed: false,

            decodeStrings: true,

            defaultEncoding: 'utf8',

            length: 0,

            writing: false,

            corked: 0,

            sync: true,

            bufferProcessing: false,

            onwrite: [Function (anonymous)],

            writecb: null,

            writelen: 0,

            bufferedRequest: null,

            lastBufferedRequest: null,

            pendingcb: 0,

            prefinished: false,

            errorEmitted: false,

            bufferedRequestCount: 0,

            corkedRequestsFree: [CorkedRequest]

          },

          writable: true,

          allowHalfOpen: true,

          _transformState: {

            afterTransform: [Function: bound afterTransform],

            needTransform: true,

            transforming: false,

            writecb: null,

            writechunk: null,

            writeencoding: null

          },

          _destroyed: false,

          _transform: [Function: normalize],

          [Symbol(kCapture)]: false

        },

        _readable: DestroyableTransform {

          _readableState: ReadableState {

            objectMode: true,

            highWaterMark: 16,

            buffer: [BufferList],

            length: 0,

            pipes: null,

            pipesCount: 0,

            flowing: null,

            ended: false,

            endEmitted: false,

            reading: true,

            sync: false,

            needReadable: true,

            emittedReadable: false,

            readableListening: true,

            resumeScheduled: false,

            destroyed: false,

            defaultEncoding: 'utf8',

            awaitDrain: 0,

            readingMore: false,

            decoder: null,

            encoding: null

          },

          readable: true,

          _events: [Object: null prototype] {

            end: [Array],

            prefinish: [Function: prefinish],

            close: [Array],

            finish: [Array],

            error: [Array],

            unpipe: [Function: onunpipe],

            drain: [Function (anonymous)],

            readable: [Function: onreadable]

          },

          _eventsCount: 8,

          _maxListeners: undefined,

          _writableState: WritableState {

            objectMode: true,

            highWaterMark: 16,

            finalCalled: false,

            needDrain: false,

            ending: false,

            ended: false,

            finished: false,

            destroyed: false,

            decodeStrings: true,

            defaultEncoding: 'utf8',

            length: 0,

            writing: false,

            corked: 0,

            sync: true,

            bufferProcessing: false,

            onwrite: [Function (anonymous)],

            writecb: null,

            writelen: 0,

            bufferedRequest: null,

            lastBufferedRequest: null,

            pendingcb: 0,

            prefinished: false,

            errorEmitted: false,

            bufferedRequestCount: 0,

            corkedRequestsFree: [CorkedRequest]

          },

          writable: true,

          allowHalfOpen: true,

          _transformState: {

            afterTransform: [Function: bound afterTransform],

            needTransform: true,

            transforming: false,

            writecb: null,

            writechunk: null,

            writeencoding: null

          },

          _destroyed: false,

          _transform: [Function: writeFile],

          [Symbol(kCapture)]: false

        },

        _readable2: DestroyableTransform {

          _readableState: ReadableState {

            objectMode: true,

            highWaterMark: 16,

            buffer: [BufferList],

            length: 0,

            pipes: null,

            pipesCount: 0,

            flowing: null,

            ended: false,

            endEmitted: false,

            reading: true,

            sync: false,

            needReadable: true,

            emittedReadable: false,

            readableListening: true,

            resumeScheduled: false,

            destroyed: false,

            defaultEncoding: 'utf8',

            awaitDrain: 0,

            readingMore: false,

            decoder: null,

            encoding: null

          },

          readable: true,

          _events: [Object: null prototype] {

            end: [Array],

            prefinish: [Function: prefinish],

            close: [Array],

            finish: [Array],

            error: [Array],

            unpipe: [Function: onunpipe],

            drain: [Function (anonymous)],

            readable: [Function: onreadable]

          },

          _eventsCount: 8,

          _maxListeners: undefined,

          _writableState: WritableState {

            objectMode: true,

            highWaterMark: 16,

            finalCalled: false,

            needDrain: false,

            ending: false,

            ended: false,

            finished: false,

            destroyed: false,

            decodeStrings: true,

            defaultEncoding: 'utf8',

            length: 0,

            writing: false,

            corked: 0,

            sync: true,

            bufferProcessing: false,

            onwrite: [Function (anonymous)],

            writecb: null,

            writelen: 0,

            bufferedRequest: null,

            lastBufferedRequest: null,

            pendingcb: 0,

            prefinished: false,

            errorEmitted: false,

            bufferedRequestCount: 0,

            corkedRequestsFree: [CorkedRequest]

          },

          writable: true,

          allowHalfOpen: true,

          _transformState: {

            afterTransform: [Function: bound afterTransform],

            needTransform: true,

            transforming: false,

            writecb: null,

            writechunk: null,

            writeencoding: null

          },

          _destroyed: false,

          _transform: [Function: writeFile],

          [Symbol(kCapture)]: false

        },

        _autoDestroy: false,

        _forwardDestroy: false,

        _forwardEnd: true,

        _corked: 0,

        _ondrain: null,

        _drained: true,

        _forwarding: false,

        _unwrite: [Function: clear],

        _unread: [Function: clear],

        _ended: false,

        [Symbol(kCapture)]: false

      },

      pipesCount: 1,

      flowing: true,

      ended: false,

      endEmitted: false,

      reading: false,

      sync: false,

      needReadable: true,

      emittedReadable: false,

      readableListening: false,

      resumeScheduled: false,

      destroyed: false,

      defaultEncoding: 'utf8',

      awaitDrain: 0,

      readingMore: false,

      decoder: null,

      encoding: null

    },

    readable: true,

    _events: [Object: null prototype] {

      end: [

        [Function: bound onceWrapper] { listener: [Function: onend] },

        [Function: bound onceWrapper] { listener: [Function: onend] }

      ],

      prefinish: [Function: prefinish],

      data: [Function: ondata]

    },

    _eventsCount: 3,

    _maxListeners: undefined,

    _writableState: WritableState {

      objectMode: true,

      highWaterMark: 16,

      finalCalled: true,

      needDrain: false,

      ending: true,

      ended: true,

      finished: false,

      destroyed: false,

      decodeStrings: true,

      defaultEncoding: 'utf8',

      length: 0,

      writing: false,

      corked: 0,

      sync: false,

      bufferProcessing: false,

      onwrite: [Function (anonymous)],

      writecb: null,

      writelen: 0,

      bufferedRequest: null,

      lastBufferedRequest: null,

      pendingcb: 1,

      prefinished: false,

      errorEmitted: false,

      bufferedRequestCount: 0,

      corkedRequestsFree: CorkedRequest {

        next: null,

        entry: null,

        finish: [Function (anonymous)]

      }

    },

    writable: false,

    _final: [Function (anonymous)],

    allowHalfOpen: true,

    _transformState: {

      afterTransform: [Function: bound afterTransform],

      needTransform: true,

      transforming: false,

      writecb: null,

      writechunk: null,

      writeencoding: 'utf8'

    },

    _destroyed: false,

    _transform: [Function: _transform],

    _flush: [Function (anonymous)],

    [Symbol(kCapture)]: false

  },

  domainThrown: false

}
```
