### ISSUE TITLE
YouTube Video Player "YouTube" Button Does Not Open YouTube

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/cgov-digital-platform#4075]
### Issue Description
On the YouTube video player, the "YouTube" button on the lower right of the video player does not open YouTube when it should on click. The only way to open YouTube from that button is to right click and Open in New Tab. This is believed to be occurring on all embedded YouTube videos, and has been confirmed to be occurring on the following pages:

https://www.cancer.gov/
https://www.cancer.gov/espanol/tipos/colorrectal/sabia-usted-cancer-colorrectal-video
https://www.cancer.gov/espanol

### Steps to reproduce the issue

1.  Go to any of the three links listed above
2. Scroll to the video on the page
3. Click play on the video and the video option buttons appear
4. Click on the YouTube button on the bottom right of the video
5. The user is not redirected to YouTube as expected
6. Right click on the YouTube button
7. Select Open in New Tab
8. The browser opens a new tab with the video in YouTube

### What's the expected result?
- When the user clicks the YouTube button on the bottom right of the video player, then the user should be redirected to YouTube to view the video.

### What's the actual result?
- When the user clicks the YouTube button on the bottom right of the video player, nothing happens.

### Additional details / screenshot
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/143126208/35d7d354-5153-46c0-aa70-c9cd13eacf4b)

**Comment by bryanpizzillo** [comment]
This is an issue with how we generate our iFrame. We need to update https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoPlayer/flexVideo.js#L22 to add `allow-popups`. There *may* be other items needed.

Additionally, when I click the play button I get the following because we do not add `allow-presentation` either:
```
Uncaught DOMException: Failed to construct 'PresentationRequest': The document is sandboxed and lacks the 'allow-presentation' flag.
    at W.initialize (https://www.gstatic.com/eureka/clank/120/cast_sender.js:83:87)
    at chrome.cast.initialize (https://www.gstatic.com/eureka/clank/120/cast_sender.js:95:137)
    at g.k.init (https://www.youtube.com/s/player/9bb09009/player_ias.vflset/en_US/remote.js:569:13)
    at dDb (https://www.youtube.com/s/player/9bb09009/player_ias.vflset/en_US/remote.js:252:40)
    at UCb (https://www.youtube.com/s/player/9bb09009/player_ias.vflset/en_US/remote.js:258:9)
    at XCb.d.disableCastApi.window.chrome.chrome.cast.chrome.cast.isAvailable.window.__onGCastApiAvailable (https://www.youtube.com/s/player/9bb09009/player_ias.vflset/en_US/remote.js:246:402)
    at chrome.cast.da (https://www.gstatic.com/eureka/clank/120/cast_sender.js:97:297)
    at https://www.gstatic.com/eureka/clank/120/cast_sender.js:97:349
    at https://www.gstatic.com/eureka/clank/120/cast_sender.js:97:471
```

**Comment by blairlearn** [comment]
Something has changed in the past three weeks.  This worked then, but now....

- Right-click on the "YouTube" button and choose to open in either "new tab" or "new window",  the video keeps playing.
- Click and let it open in the same window, the browser displays "www.youtube.com is blocked."
  - Copy the URL from the address bar and paste it into a new window, that won't work either.
- Failures occur in Edge and Chrome.
- Works in Firefox and Safari.
